"""initial schema

Revision ID: 5f41bb64795d
Revises: 
Create Date: 2026-04-20 23:57:38.424444
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f41bb64795d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('taxonomy_path', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_publication', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_mentions_source_url')
    )
    op.create_index('ix_mentions_content_hash', 'mentions', ['content_hash'], unique=False)
    op.create_index('ix_mentions_ingested_at', 'mentions', ['ingested_at'], unique=False)
    op.create_index('ix_mentions_published_at', 'mentions', ['published_at'], unique=False)
    op.create_index('ix_mentions_source_publication', 'mentions', ['source_publication'], unique=False)
    op.create_index('ix_mentions_source_type', 'mentions', ['source_type'], unique=False)
    op.create_table('briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('subheadline', sa.Text(), nullable=True),
    sa.Column('opening_paragraph', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_client_id', 'entities', ['client_id'], unique=False)
    op.create_index('ix_entities_type', 'entities', ['type'], unique=False)
    op.create_table('mention_analysis',
    sa.Column('mention_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('themes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('key_claims', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('action_triggers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.PrimaryKeyConstraint('mention_id')
    )
    op.create_table('mention_entities',
    sa.Column('mention_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.PrimaryKeyConstraint('mention_id', 'entity_id')
    )
    op.create_table('narratives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_trajectory', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('velocity_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narratives_entity_id', 'narratives', ['entity_id'], unique=False)
    op.create_index('ix_narratives_status', 'narratives', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('narrative_id', sa.UUID(), nullable=True),
    sa.Column('mention_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_mentions',
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('mention_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('narrative_id', 'mention_id')
    )
    op.create_table('action_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('draft_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_drafts')
    op.drop_table('narrative_mentions')
    op.drop_table('alerts')
    op.drop_index('ix_narratives_status', table_name='narratives')
    op.drop_index('ix_narratives_entity_id', table_name='narratives')
    op.drop_table('narratives')
    op.drop_table('mention_entities')
    op.drop_table('mention_analysis')
    op.drop_index('ix_entities_type', table_name='entities')
    op.drop_index('ix_entities_client_id', table_name='entities')
    op.drop_table('entities')
    op.drop_table('briefs')
    op.drop_index('ix_mentions_source_type', table_name='mentions')
    op.drop_index('ix_mentions_source_publication', table_name='mentions')
    op.drop_index('ix_mentions_published_at', table_name='mentions')
    op.drop_index('ix_mentions_ingested_at', table_name='mentions')
    op.drop_index('ix_mentions_content_hash', table_name='mentions')
    op.drop_table('mentions')
    op.drop_table('clients')
    # ### end Alembic commands ###
